spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:news
  liquibase:
    enabled: false
  h2:
    console:
      path: /console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: true
        format_sql: false
    show-sql: true


